#!name=RedMode_Xwuan
#!desc=Unlock RedMode Pro (Based on Locket Method) - Build by Gemini

[Script]
# ~ Sửa dữ liệu gói cước Pro
redmode_sub = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/v1\/(subscribers\/[^/]+$|receipts$), script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/RedMode/redmode_sub.js, requires-body=true, max-size=-1, timeout=120

# ~ Xóa Header ETag để tránh lỗi server
redmode_header = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/v1\/(subscribers|receipts), script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/RedMode/redmode_header.js, timeout=120

[MITM]
hostname = %APPEND% api.revenuecat.com
