#!name=RedMode_Xwuan
#!desc=Unlock RedMode Pro
#!author=Xwuan

[General]
# Giả lập User-Agent nếu cần
user-agent = RedMode/1.0.0 (iPhone; iOS 18; Scale/3.00)

[Script]
# ~ Unlock Subscription
redmode_sub = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/v1\/(subscribers\/[^/]+$|receipts$), script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/RedMode/redmode_sub.js, requires-body=true, max-size=-1, timeout=120

# ~ Delete ETag Header
redmode_header = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/v1\/(subscribers|receipts), script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/RedMode/redmode_header.js, timeout=120

[MITM]
hostname = %APPEND% api.revenuecat.com, raw.githubusercontent.com
