#!name = 2 in 1 - Spotify & Locket Xwuan
#!desc = Spotify + Locket Premium Crack By ie.1w3n
#!author = ie.1w3n

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26.3; Scale/3.00)

[Script]
# ===== Spotify =====
spotify-header = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$,script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Spotify/spotify-qx-header.js,requires-body=0,timeout=10
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Spotify/spotify-proto.js,requires-body=1,binary-body-mode=1,timeout=10
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Spotify/spotify-json.js,requires-body=0,timeout=10

# ===== Locket =====
revenuecat = type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$),script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Locket/locketXn.js,requires-body=true,max-size=-1,timeout=120
deleteHeader = type=http-request,pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers),script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Locket/deleteHeader.js,timeout=120

[MITM]
hostname = %APPEND%, spclient.wg.spotify.com, *spclient.spotify.com, api.revenuecat.com, raw.githubusercontent.com
